### ISSUE TITLE
Modal overlay does not extend to the bottom

### ISSUE THREAD

**Issue by nlukic97** [nlukic97/chess_platform#20]
Hey @knlju, It appears that the overlay does not go all the way to the bottom of the screen:

![image](https://user-images.githubusercontent.com/56925545/148682046-af40cf83-4996-4e47-975d-aafe35c2c6da.png)

**Comment by knlju** [comment]
> Hey @knlju, It appears that the overlay does not go all the way to the bottom of the screen:
> 
> ![image](https://user-images.githubusercontent.com/56925545/148682046-af40cf83-4996-4e47-975d-aafe35c2c6da.png)

Good catch! Position fixed instead of absolute. I will merge this weekend.
